verbose: false

repository:
    path: github.com/robinmarechal/asteriskk_exporter
    
go:
    version: 1.16
    cgo: false

build:
    binaries:
        - name: asteriskk_exporter
          path: .

    flags: -a -tags netgo
    
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
    prefix: asteriskk_exporter
    files:
        - README.md
        - LICENSE
        - asteriskk_exporter.service

crossbuild:
    platforms:
        - darwin/amd64
        - darwin/386
        - linux/amd64
        - linux/386
        - linux/arm
        - linux/arm64
